# Generated by Django 6.0.3 on 2026-04-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_pendingemailchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingemailchange',
            name='send_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='email_change_locked',
            field=models.BooleanField(default=False),
        ),
    ]
