# Generated by Django 6.0.3 on 2026-03-13 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_note', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='submission_evidence/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('requirement_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='submissions.badgesubmission')),
            ],
        ),
    ]
