# Generated by Django 6.0.3 on 2026-03-17 02:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0009_alter_badge_category_alter_badge_is_active'),
        ('submissions', '0002_submissionevidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='badgesubmission',
            index=models.Index(fields=['scout', 'status'], name='sub_scout_status_idx'),
        ),
        migrations.AddIndex(
            model_name='badgesubmission',
            index=models.Index(fields=['scout', 'requirement', 'status'], name='sub_scout_req_status_idx'),
        ),
    ]
