# Generated by Django 6.0.3 on 2026-03-23 02:06

from django.conf import settings
from django.db import migrations
from django.db.models import Count


def deduplicate_submissions(apps, schema_editor):
    BadgeSubmission = apps.get_model("submissions", "BadgeSubmission")
    STATUS_PRIORITY = {"approved": 0, "submitted": 1, "rejected": 2, "draft": 3}

    duplicates = (
        BadgeSubmission.objects
        .values("scout_id", "requirement_id")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )
    for dup in duplicates:
        rows = list(
            BadgeSubmission.objects
            .filter(scout_id=dup["scout_id"], requirement_id=dup["requirement_id"])
        )
        rows.sort(key=lambda r: (STATUS_PRIORITY.get(r.status, 99), -r.updated_at.timestamp()))
        ids_to_delete = [r.id for r in rows[1:]]
        BadgeSubmission.objects.filter(id__in=ids_to_delete).delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('badges', '0009_alter_badge_category_alter_badge_is_active'),
        ('submissions', '0003_badgesubmission_sub_scout_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(deduplicate_submissions, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='badgesubmission',
            unique_together={('scout', 'requirement')},
        ),
    ]
