# Generated by Django 6.0.3 on 2026-03-23 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0009_alter_badge_category_alter_badge_is_active'),
        ('submissions', '0004_alter_badgesubmission_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeHandout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField()),
                ('handed_out', models.BooleanField(default=False)),
                ('handed_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handouts', to='badges.badge')),
                ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('scout', 'badge')},
            },
        ),
    ]
