# Generated by Django 6.0.3 on 2026-04-12 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_badgehandout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScouerNotificationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('state_date', models.DateField()),
                ('first_sent_today', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PendingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(db_index=True, default=False)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_notifications', to='submissions.badgesubmission')),
            ],
            options={
                'indexes': [models.Index(fields=['recipient_email', 'sent'], name='pn_email_sent_idx')],
                'unique_together': {('submission', 'recipient_email')},
            },
        ),
    ]
