# Generated by Django 6.0.3 on 2026-05-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0003_financialstatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatement',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='statements', to='treasury.account'),
        ),
    ]
