# Generated by Django 6.0.3 on 2026-05-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0004_add_accounts_to_statement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialstatement',
            options={'ordering': ['-generated_at']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_opening_balance',
            field=models.BooleanField(default=False),
        ),
    ]
