# Generated by Django 6.0.3 on 2026-03-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('vertical_skills', 'Vertical Skills'), ('sailing_skills', 'Sailing Skills'), ('scoutcraft_skills', 'Scoutcraft Skills'), ('camping_skills', 'Camping Skills'), ('trail_skills', 'Trail Skills'), ('winter_skills', 'Winter Skills'), ('paddling_skills', 'Paddling Skills'), ('aquatic_skills', 'Paddling Skills'), ('emergency_skills', 'Emergency Skills'), ('personal_progression', 'Personal Progression')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
