# Generated by Django 6.0.3 on 2026-03-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_badgerequirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='description',
        ),
        migrations.AlterField(
            model_name='badge',
            name='category',
            field=models.CharField(choices=[('vertical_skills', 'Vertical Skills'), ('sailing_skills', 'Sailing Skills'), ('scoutcraft_skills', 'Scoutcraft Skills'), ('camping_skills', 'Camping Skills'), ('trail_skills', 'Trail Skills'), ('winter_skills', 'Winter Skills'), ('paddling_skills', 'Paddling Skills'), ('aquatic_skills', 'Aquatic Skills'), ('emergency_skills', 'Emergency Skills'), ('personal_progression', 'Personal Progression')], max_length=50),
        ),
    ]
