# Generated by Django 6.0.3 on 2026-03-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_remove_badge_description_alter_badge_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgerequirement',
            name='hint',
            field=models.TextField(blank=True),
        ),
    ]
