# Generated by Django 6.0.3 on 2026-03-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_badgerequirement_hint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badgerequirement',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='badge',
            name='level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='category',
            field=models.CharField(choices=[('vertical_skills', 'Vertical Skills'), ('sailing_skills', 'Sailing Skills'), ('scoutcraft_skills', 'Scoutcraft Skills'), ('camping_skills', 'Camping Skills'), ('trail_skills', 'Trail Skills'), ('winter_skills', 'Winter Skills'), ('paddling_skills', 'Paddling Skills'), ('aquatic_skills', 'Aquatic Skills'), ('emergency_skills', 'Emergency Skills'), ('personal_progression', 'Personal Progression'), ('awards', 'Awards')], max_length=50),
        ),
    ]
