# Generated by Django 6.0.3 on 2026-03-15 22:23

import re
from django.db import migrations


def populate_badge_levels(apps, schema_editor):
    Badge = apps.get_model('badges', 'Badge')
    for badge in Badge.objects.all():
        match = re.search(r'\s(\d+)$', badge.name)
        if match:
            badge.level = int(match.group(1))
            badge.save()


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0005_add_level_to_badge'),
    ]

    operations = [
        migrations.RunPython(populate_badge_levels, migrations.RunPython.noop),
    ]
