# Generated by Django 6.0.3 on 2026-03-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0008_set_pp_intro_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='category',
            field=models.CharField(choices=[('vertical_skills', 'Vertical Skills'), ('sailing_skills', 'Sailing Skills'), ('scoutcraft_skills', 'Scoutcraft Skills'), ('camping_skills', 'Camping Skills'), ('trail_skills', 'Trail Skills'), ('winter_skills', 'Winter Skills'), ('paddling_skills', 'Paddling Skills'), ('aquatic_skills', 'Aquatic Skills'), ('emergency_skills', 'Emergency Skills'), ('personal_progression', 'Personal Progression'), ('awards', 'Awards')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='badge',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
