# Generated by Django 6.0.3 on 2026-04-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0009_alter_badge_category_alter_badge_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='badges/'),
        ),
    ]
